### ISSUE TITLE
An issue on android 

### ISSUE THREAD

**Issue by bluedusk** [jacklam718/react-native-button-component#8] opened 2017-02-21 06:31 UTC
Hi, I run into some issue when try to use this in android, I imported the component and my app starts with no error, but the buttons are not showing. Should I run `react-native link` first?  Many thanks.

when I run  `react-native link`  I got error:

>    events.js:141
      throw er; // Unhandled 'error' event
      ^

>  Error: spawn bash ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by jacklam718** [comment] 2017-02-21 07:50
@bluedusk 
Yeah, you need to run `react-native link` after this package installed on your project.
I will investigate it and give you feedback  soon. Thank you for reporting this issue!

Can you give me more info:
1. What your Android version?
2. Can you post all console logs here?
3. Which version of `react-native-button-component` are you install? Is the latest one `v0.1.12`?

**Comment by mikeon** [comment] 2017-02-24 19:06
I've got the same as @bluedusk 
Android >5, MIUI 8
version of component - latest


```
>npm install --save react-native-button-component
cell@0.0.1 C:\Projects\buzz\cell
`-- react-native-button-component@0.1.13
  +-- babel-preset-react-native-stage-0@1.0.1
  | +-- babel-plugin-transform-class-constructor-call@6.22.0
  | | `-- babel-plugin-syntax-class-constructor-call@6.18.0
  | +-- babel-plugin-transform-decorators-legacy@1.3.4
  | | `-- babel-plugin-syntax-decorators@6.13.0
  | +-- babel-plugin-transform-do-expressions@6.22.0
  | | `-- babel-plugin-syntax-do-expressions@6.13.0
  | +-- babel-plugin-transform-exponentiation-operator@6.22.0
  | | +-- babel-helper-builder-binary-assignment-operator-visitor@6.22.0
  | | | `-- babel-helper-explode-assignable-expression@6.22.0
  | | `-- babel-plugin-syntax-exponentiation-operator@6.13.0
  | +-- babel-plugin-transform-export-extensions@6.22.0
  | | `-- babel-plugin-syntax-export-extensions@6.13.0
  | `-- babel-plugin-transform-function-bind@6.22.0
  |   `-- babel-plugin-syntax-function-bind@6.13.0
  +-- react-native-circular-progress@0.0.8  (git://github.com/jacklam718/react-native-circular-progress.git#1f05129e188e166744ae8ee0455ba9a3ae744353)
  `-- react-native-linear-gradient@2.0.0


>react-native link
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn bash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by jacklam718** [comment] 2017-02-25 13:16
@bluedusk @mikeon Are you guys using Windows machine?

**Comment by mikeon** [comment] 2017-02-26 09:09
@jacklam718 Yes, Windows 10.

**Comment by jacklam718** [comment] 2017-02-26 09:21
@bluedusk @mikeon Can you install this version `0.1.14`? Please let me know if there are any issues.

**Comment by jacklam718** [comment] 2017-02-26 14:32
@mikeon Did you try?

**Comment by mikeon** [comment] 2017-02-26 21:18
@jacklam718 yes, it's properly run, without error. 

But using this component is a little bit confusing. Pasted this: 

```
        <RoundButton
          onPress={() => {this.props.sendReady(gameChannel, playerName, gameId)}}
          text="Button"
        >
        </RoundButton>
```
But any button appear, so probably I miss something or simple use scenario is not working properly.

**Comment by jacklam718** [comment] 2017-03-17 09:07
@mikeon what are you confused about?

**Comment by jacklam718** [comment] 2017-03-17 09:12
@mikeon I want to confirm with you, is the issue is solved? If so I will closed this issue. If you have other issues that are not relevant to this issue, please open a new issue.

**Closed** 2017-04-23 07:06 UTC
